s add speed -0.25
d add speed +0.25
1 set speed 1.0
2 set speed 2.0
ENTER cycle fullscreen
UP add volume 2
DOWN add volume -2
RIGHT seek 5
LEFT seek -5
PGUP add sub-pos -1
PGDWN add sub-pos +1
0 seek 0 absolute